# Generated by Django 3.2.9 on 2021-11-25 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='repo_url',
            field=models.URLField(blank=True, max_length=1024, verbose_name='Ссылка на репозиторий'),
        ),
    ]
